apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-ingress-controller
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - configmap-nginx-ingress-controller-helm-chart-value-overrides.yaml
